### PR TITLE
Add Winners Section

### LINKED ISSUE #20: Add Winners section in 2017 tab
### Expected Behaviour
Add `Winners and Finalists` section in 2017 GCI tab.

### Do you want to work on it?
Yes

@RishabhJain2018

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #20 .
@RishabhJain2018 

screencapture-127-0-0-1-4000-2017-2018-12-06-19_21_04 1

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please center align the list.

**Comment by gautamjajoo** [comment]
Updated!! @RishabhJain2018 
capture

**Comment by RishabhJain2018** [comment]
@gautamjajoo Can you please paste the screenshot of full page?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 
screencapture-127-0-0-1-4000-2017-2018-12-17-15_36_34

**Comment by RishabhJain2018** [comment]
Thanks @gautamjajoo for adding this section.

**Pull request merged**
