### PR TITLE
Fix #25: Update website according to 2019

### LINKED ISSUE #25: Update GCI according to 2019
The GCI website needs to be updated with the latest additions (2019 mentors and finalists) and mentioning the EvalAI-ngx and EvalAI-CLI repos.
@RishabhJain2018

### PR DESCRIPTION
**Pull request by nikochiko**
Update GCI website according to 2019 details.
Fixes #25

### CODE REVIEW

**Comment by nikochiko** [comment]
Screenshot_2020-02-14 CloudCV - Google Code-In

**Comment by nikochiko** [comment]
@vkartik97 Done!
image

**Comment by nikochiko** [comment]
The archived 2018 page:
image

**Comment by RishabhJain2018** [comment]
Thanks, @nikochiko for adding it quickly and @vkartik97 for the review.

**Pull request merged**
