### PR TITLE
Update team for GCI 2018

### PR DESCRIPTION
**Pull request by thatbrguy**
- Added Mentors and Org Admin names in ascending order for GCI 2018

### CODE REVIEW

**Comment by thatbrguy** [comment]
@RishabhJain2018

**Comment by RishabhJain2018** [comment]
@thatbrguy Can you please paste the screenshot of the UI?

**Comment by thatbrguy** [comment]
@RishabhJain2018 Sure, here it is:
UI

**Comment by thatbrguy** [comment]
@RishabhJain2018 Here's the UI:
ui

**Comment by thatbrguy** [comment]
@RishabhJain2018 Here's the UI:
ui

**Pull request merged**
